name: GuiShop
main: GuiShop\Main
version: 1.0.0
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
author: ChalixMC Developement Team
description: ShopUI for servers!
commands:
 shop:
  description: Opens the shop gui
